CREATE TABLE IF NOT EXISTS proj_school
(
    ID INT AUTO_INCREMENT NOT NULL,
    SCHOOL_NAME VARCHAR(200) NOT NULL,
    SCHOOL_CITY VARCHAR(100) NOT NULL,
    SCHOOL_ADDRESS VARCHAR(200) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS proj_grade
(
    ID INT AUTO_INCREMENT NOT NULL,
    GRADE_NUMBER INT NOT NULL,
    LITERA VARCHAR(3) default NULL,
    SCHOOL_ID INT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (SCHOOL_ID) REFERENCES proj_school(ID)
);

CREATE TABLE IF NOT EXISTS proj_exercise
(
    ID INT AUTO_INCREMENT NOT NULL,
    EXERCISE_CONDITION VARCHAR(900) NOT NULL,
    ANSWER VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS proj_subject
(
    ID INT AUTO_INCREMENT NOT NULL,
    SUBJECT_NAME VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS proj_variant
(
    ID INT AUTO_INCREMENT NOT NULL,
    GENERATOR_CODE varchar(900),
    COUNT int NOT NULL,
    SUBJECT_ID INT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES proj_subject(ID)
);

CREATE TABLE IF NOT EXISTS proj_exercise_variant
(
    EXERCISE_ID INT NOT NULL,
    VARIANT_ID INT NOT NULL,

    FOREIGN KEY (EXERCISE_ID) REFERENCES proj_exercise(ID),
    FOREIGN KEY (VARIANT_ID) REFERENCES proj_variant(ID)
);

CREATE TABLE IF NOT EXISTS proj_role
(
    ID INT AUTO_INCREMENT NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS proj_rights
(
    ID INT AUTO_INCREMENT NOT NULL,
    RIGHT_NAME VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS proj_role_rights
(
    ROLE_ID INT NOT NULL,
    RIGHT_ID INT NOT NULL,

    FOREIGN KEY (ROLE_ID) REFERENCES proj_role(ID),
    FOREIGN KEY (RIGHT_ID) REFERENCES proj_rights(ID)
);

CREATE TABLE IF NOT EXISTS proj_user
(
    ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    MAIL VARCHAR(200) NOT NULL,
    ROLE_ID INT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES proj_role(ID)
);

CREATE TABLE IF NOT EXISTS proj_user_grade
(
    GRADE_ID INT NOT NULL,
    USER_ID INT NOT NULL,

    FOREIGN KEY (GRADE_ID) REFERENCES proj_grade(ID),
    FOREIGN KEY (USER_ID) REFERENCES proj_user(ID)
);

CREATE TABLE IF NOT EXISTS proj_variant_user
(
    VARIANT_ID INT NOT NULL,
    USER_ID INT NOT NULL,

    FOREIGN KEY (VARIANT_ID) REFERENCES proj_variant(ID),
    FOREIGN KEY (USER_ID) REFERENCES proj_user(ID)
);